version: '3'

services:
  webserver:
    build:
      context: ./webserver
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html

  ansible:
    build:
      context: ./ansible
    volumes:
      - ./ansible:/ansible
    depends_on:
      - webserver
